### ISSUE TITLE
Question about PostConstruct initialization

### ISSUE THREAD

**Issue by mklueh** [AdamBien/mockend#1]
Hi Adam,

out of curiosity, what is the reason for initializing the HashMap in the @PostConstruct method here instead of doing a field or constructor initialization?

```
public class CRUDResource {

    Map<String, JsonObject> store;
    
    @PostConstruct
    public void init() {
        this.store = new HashMap<>();
    }

}
```

Thanks

**Comment by AdamBien** [comment]
Here it wouldn't matter. However: anything which can go wrong, must not be instantiated in the constructor, rather than in the @PostConstruct. Reason: nicer exceptions :-)

I'm relying on @PostConstruct initialization -> is easier to review. However: that is just a convention.

**Comment by mklueh** [comment]
valid point, thanks for clarifying  :)
